version: '3.8'

services:
  starbase1-monitor:
    build: .
    container_name: starbase1_system_monitor
    image: vonholtencodes/starbase1-monitor:latest
    ports:
      - "5000:5000"
    volumes:
      # Mount host system directories for monitoring (read-only)
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/os-release:ro
      # Optional: Docker socket for container monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Container-specific environment variables
      - CONTAINER_MODE=true
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - REFRESH_INTERVAL=360
      - TZ=UTC
    # Privileged mode for hardware access (temperatures, BIOS)
    privileged: true
    # Restart policy
    restart: unless-stopped
    # Optional: Use host network for better integration
    # network_mode: host
    labels:
      - "com.vonholtencodes.app=starbase1-monitor"
      - "com.vonholtencodes.version=1.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s